name: Integration Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  integration-tests:
    name: "Python ${{ matrix.python-version }} + Kafka ${{ matrix.kafka-version }}"
    runs-on: ubuntu-20.04
    env:
      TOX_SUITE: int
      KAFKA_VERSION: "${{ matrix.kafka-version }}"

    strategy:
      matrix:
        python-version: ["3.9"]
        kafka-version: ["1.1.1"]

    steps:
    - uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sudo apt-get install -yqq build-essential libsnappy-dev

    - name: Cache Kafka tarballs
      # Cache Kafka server tarballs to be nice to the Apache servers.
      uses: actions/cache@v2
      with:
        path: servers/dist
        key: kafka-${{ matrix.kafka-version }}
        restore-keys: |
          kafka-${{ matrix.kafka-version }}
          kafka-

    - name: "Set up Python ${{ matrix.python-version }}"
      uses: actions/setup-python@v2
      with:
        python-version: "${{ matrix.python-version }}"

    - name: Install dependencies
      run: |
        set -xeu
        python -VV
        python -m pip install tox tox-gh-actions

    - name: Tox
      run: |
        python -m tox
